channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - cutadapt=2.3
  - r-base=3.6.3
  - r-tidyverse=1.3
  - r-vegan=2.5
  - r-dendextend=1.14
  - r-viridis=0.6
  - bioconductor-phyloseq=1.30
  - bioconductor-deseq2=1.26
  - bioconductor-dada2=1.14
  - bioconductor-decipher=2.14
  - bioconductor-decontam=1.6
  - r-biocmanager=1.30
  - r-matrix=1.3_2
