channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - cutadapt
  - r-base
  - r-tidyverse
  - r-vegan
  - r-dendextend
  - r-viridis
  - bioconductor-phyloseq
  - bioconductor-deseq2
  - bioconductor-dada2
  - bioconductor-decipher
  - bioconductor-decontam
  - r-biocmanager
  - r-matrix
