channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - cutadapt=4.2
  - r-base=4.0
  - r-tidyverse=1.3
  - r-vegan=2.6
  - r-dendextend=1.16
  - r-viridis=0.6
  - bioconductor-phyloseq=1.34
  - bioconductor-deseq2=1.30
  - bioconductor-dada2=1.18
  - bioconductor-decipher=2.18
  - bioconductor-decontam=1.10
  - r-biocmanager=1.30
  - r-matrix=1.4
