install.packages("vegan")
install.packages("dendextend")
install.packages("tidyr")
install.packages("viridis")

source("https://bioconductor.org/biocLite.R")
biocLite(suppressUpdates = FALSE)
biocLite("phyloseq")
biocLite("DESeq2")
biocLite("ShortRead", suppressUpdates = FALSE)

install.packages("devtools")
library("devtools")
devtools::install_github("tidyverse/ggplot2")
devtools::install_github("benjjneb/dada2")
